### PR TITLE
Add ListenAndServeTLScerts()

### PR DESCRIPTION
**Pull request by rbg**
My use case is such that i have the certificate and key information already loaded in memory and therefore do not require the ca/cert/key files to be re-read. This new interface provides a means to start a server using the memory based cert/key.

### CODE REVIEW

**Comment by tylerb** [comment]
Given that this is (typically) a one-time operation, I don't see there being much of a downside to re-reading the files using the already provided functions. Is there a particular restriction that is in place for you?

**Comment by rbg** [comment]
The source of the certs/keys may not be a file, but rather passed via environment variables or have been already embedded in code as a constant.

**Comment by tylerb** [comment]
Sounds good.

To make this more flexible, I think it may be best to rename the function to `ListenAndServeTLSConfig` and take a `*tls.Config` as the argument.

**Comment by rbg** [comment]
yes, i like that much better .. I will do that..

**Pull request closed without merging**
