### PR TITLE
added new go1.7 context

### PR DESCRIPTION
**Pull request by awalterschulze**
As discussed in https://github.com/tylerb/graceful/issues/78#issuecomment-248564988

### CODE REVIEW

**Comment by awalterschulze** [comment]
So it fails for older versions of go.
This is expected.

**Comment by tylerb** [comment]
Failing for older versions of Go is unacceptable. I would like to maintain compatibility with Go versions back to 1.3.3, at least for now.

**Comment by tylerb** [comment]
I am interested in using `Context` for graceful, but I am failing to see how it will be of benefit given your example in #90. I personally haven't used `Context` for anything yet, so I would love if you could give me some scenarios where this would be better than having `graceful` handle the interrupt for you.

As it stands now, it seems that the context adds a lot of boilerplate (signal handling, etc) that is currently contained inside `graceful` and handled for you. What's the motivation for this change?

In addition, in order for this to be accepted, it will need to maintain compatibility back to `go1.3.3`. This could be achieved by using build tags such as `// +build go1.3 !go1.7` and `// +build go1.7`. However, that doesn't feel too great, especially if it results in significant code duplication.

**Comment by awalterschulze** [comment]
You could use golang/x/net/context to keep things compatible with older go versions.

It makes it easier for me to test graceful given I have control over when the server stops.

When you have a process which not only serves a page, but also does some processing on a queue you might want to be able to cancel both in the same way.

But if you aren't convinced thats fair.  I hated context to start with, but now I am falling in love with in.  It is your project you should decide what you think is best. 
At the moment I am just keeping graceful out of my tests, but it would be really nice not to have to do that.  Since then I also do not have to separate my handle and process functions and can just have a run function which I can cancel at any time.

**Comment by tylerb** [comment]
As it stands now, graceful provides a mechanism for alerting when shutdown has occurred, and a mechanism for manually stopping the server.

Those two mechanisms should allow you to easily have it run alongside your other code and interact with the context to shut it down as well.

Given that, I feel the benefits of this change do not outweigh the costs.

That being said, I have been interested in a rewrite for some time now, and, pending some research and thought, I would be comfortable with making that rewrite be 1.7+ only so that it can work off context, as that seems to be the way things are headed in general.

**Comment by awalterschulze** [comment]
Fair point :)

I look forward to your rewrite :)

**Comment by F21** [comment]
@awalterschulze My apologies for sending you on a wild goose chase! I should have thought this one through a lot better.

**Comment by awalterschulze** [comment]
No problem it only took a couple of minutes.
Sometimes I also have to see something before I know whether I want it :)

**Pull request closed without merging**
