### PR TITLE
Support HTTP/2 for TLS servers.

### LINKED ISSUE #66: Doesn't serve http/2
I have a simple https webserver like so:

```go
package main

import (
	//"gopkg.in/tylerb/graceful.v1"
	"net/http"
)

func main() {

	srv := &http.Server{Addr: ":https"}
	srv.ListenAndServeTLS("cert.crt", "key.pem")
}
```

If I build it and run in and then access it via Chrome, I can see that it uses http/2 (h2) from the dev tools.

If I add graceful into the mix, it only uses http/1.1:

```go
package main

import (
	"gopkg.in/tylerb/graceful.v1"
	"net/http"
	"time"
)

func main() {

	srv := &http.Server{Addr: ":https"}
	graceful.ListenAndServeTLS(srv, "cert.crt", "key.pem", 10*time.Second)
}
```

### PR DESCRIPTION
**Pull request by F21**
This PR adds support for HTTP/2 servers when it is started in https mode.

It follows the same behavior as the Go `net/http` server. Start the graceful server using the following automatically enables http/2: `ListenAndServeTLS()`, `server.ListenAndServeTLS()`, `server.ListenAndServeTLSConfig()`.

If the user wants to create his own listener and pass that in to `server.Serve()`, he will need to set `server.TLSConfig` to enable `http/2`. This is consistent with `http.Server`'s behavior.

Go 1.6+ is required for `http/2` support.

Closes #66.

### CODE REVIEW

**Comment by F21** [comment]
It looks like `request.Cancel` was introduced in Go 1.5 and is required by the `golang/x/net/http2` package. 

The reason why this package was included was because I needed to use `http2.ConfigureTransport` to enable `HTTP/2` for the client during test as I needed to allow insecure (self-signed) certificates. See https://github.com/golang/go/blob/605e751b53a8bec7d1f51b2ccc0093e063358dc6/src/net/http/transport.go#L200

Here are some solutions:
- Remove the tests. I don't think this is a good idea as getting it to serve http/2 is somewhat tricky as the `net/http` uses a bit too much magic (imo) to upgrade to http/2. The tests prevents http/2 from being broken in the future.

- Allow test failures for Go 1.3 and 1.4: Might reduce visibility of test failures, but is it something we can cope with?

- Remove support for Go 1.3 and 1.4: 1.3 last had a release in late 2014. I believe the 1.4 released late last year is probably the last release for the 1.4 series. Are people still using these old releases? If not, maybe we can drop support for these 2 releases.

**Comment by mb0** [comment]
to fix the dependency problem i think you can put it in a new test file with a build tag for // +build go1.5

see https://golang.org/pkg/go/build/

i am not sure if that works but it is worth a try.

**Comment by F21** [comment]
@mb0, hmm, that didn't work. :disappointed:

**Comment by F21** [comment]
@mb0 I neglected a blank line between the build directive and the code. It works perfectly now! :smile:

**Comment by tylerb** [comment]
Thanks for your work on this, @F21 and @mb0. Sorry I've not been more responsive.

LGTM

**Pull request merged**
